# Generated by Django 5.1 on 2024-08-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='price',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
